site_name: LinuxMirrors
repo_name: LinuxMirrors
repo_url: https://github.com/SuperManito/LinuxMirrors
edit_uri: edit/main/docs/
copyright: 'Copyright &copy; 2025 <a href="https://github.com/SuperManito" target="_blank" rel="noopener noreferrer">SuperManito</a>'

nav:
  - "介绍": index.md
  - "使用方法": use/index.md
  - "软件源列表": mirrors/index.md
  - "容器工具": other/index.md
  - "更新日志": changelog/index.md
  - "社区": community/index.md
  - "赞助": sponsor/index.md

extra_javascript:
  - https://unpkg.com/vue/dist/vue.global.prod.js
  - https://unpkg.com/tdesign-vue-next/dist/tdesign.min.js
  - assets/js/modules/tdesign-theme.js
  - assets/js/components/orama-ui/config.js
  - assets/js/components/orama-ui/index.js
  - assets/js/useThemeTransition.js
  - assets/js/common.js
  - assets/js/component.js
  - assets/js/components/mirrors-table/data.js
  - assets/js/components/mirrors-table/index.js
extra_css:
  - https://unpkg.com/tdesign-vue-next/dist/tdesign.min.css
  - assets/css/orama-ui.css
  - stylesheets/extra.css

theme:
  logo: assets/images/brand/svg/logo-light.svg
  name: material
  custom_dir: docs/theme
  language: zh
  favicon: assets/favicon.ico
  font: false
  icon:
    repo: simple/github
    edit: material/file-document-edit-outline
    view: material/file-eye-outline
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: fontawesome/regular/lightbulb
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme)"
      scheme: system
      toggle:
        icon: material/brightness-auto
        name: 跟随系统
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: octicons/sun-16
        name: 亮色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: octicons/moon-16
        name: 暗黑模式
  features:
    - header.autohide
    - navigation.top
    - navigation.tabs
    - navigation.path
    # - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.footer
    - navigation.prune
    - navigation.tracking
    - navigation.sections
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
extra:
  generator: false
  homepage: https://linuxmirrors.cn
  social:
    - icon: simple/github
      link: https://github.com/SuperManito/LinuxMirrors
      name: GitHub
    - icon: simple/gitee
      link: https://gitee.com/SuperManito/LinuxMirrors
      name: Gitee
    - icon: simple/gitcode
      link: https://gitcode.com/SuperManito/LinuxMirrors
      name: GitCode
  analytics:
    provider: google
    property: G-WG7T40F7YP
markdown_extensions:
  - toc:
      permalink: "#"
      permalink_title: 链接
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - abbr
  - tables
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/assets/images/icon/custom
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 简体中文
        - locale: zh-Hant
          name: 繁體中文
          nav_translations:
            "介绍": 介紹
            "使用方法": 使用方法
            "软件源列表": 軟體源列表
            "容器工具": 容器工具
            "更新日志": 更新日誌
            "社区": 社群
            "赞助": 贊助
          build: true
          theme:
            palette:
              - media: "(prefers-color-scheme)"
                toggle:
                  name: 跟隨系統
              - media: "(prefers-color-scheme: light)"
                toggle:
                  name: 亮色模式
              - media: "(prefers-color-scheme: dark)"
                toggle:
                  name: 暗黑模式
        - locale: en
          name: English
          nav_translations:
            "介绍": Introduction
            "使用方法": Use
            "软件源列表": Mirrors List
            "容器工具": Container Tools
            "更新日志": Changelog
            "社区": Community
            "赞助": Sponsor
          build: true
          theme:
            palette:
              - media: "(prefers-color-scheme)"
                toggle:
                  name: Follow System
              - media: "(prefers-color-scheme: light)"
                toggle:
                  name: Light Mode
              - media: "(prefers-color-scheme: dark)"
                toggle:
                  name: Dark Mode
  - search:
      # lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags
  - termynal
  # - minify:
  #     minify_js: true
  #     minify_css: true
  #     htmlmin_opts:
  #         remove_comments: true
  #     cache_safe: false
  #     js_files:
  #       - assets/js/useThemeTransition.js
  #       - assets/js/common.js
  #       - assets/js/component.js
  #       - assets/js/components/mirrors-table/data.js
  #       - assets/js/components/mirrors-table/index.js
